### ISSUE TITLE
Some simple component suggestion... 

### ISSUE THREAD

**Issue by mamarilmanson** [codeomnitrix/bootstrap-snippets#4]
I would just shortcut it... emmet style...

a) .container>.row.div
b) .row>div
(so there would be options)

c) .row>img.img-responsive

just what I'm commonly using... :)

**Comment by codeomnitrix** [comment]
Hey mamarilmanson, Thanks for using the plugin. Please fork it and customize it as per your need :)

Thanks

**Comment by mamarilmanson** [comment]
uhm... ok... thanks... :)

-______-
